#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GOWL.Resource", IsApplication=true)]

namespace GOWL
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlavandshukFyr = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Breezanddijk = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bunkermuseum = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dengemleby = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fiskrestaurant = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int framePreview = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hamburghafen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int JourneyPreviewUnfold = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int kabelpark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int kleinemeerjungfrau = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Logo_komplett_Final_mini = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Logo_komplett_Final_mini_alt = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int molsbjerge = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Moodboards_Interessen_01 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Moodboards_Interessen_01_confirmed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Moodboards_Interessen_02 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Moodboards_Interessen_02_confirmed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Moodboards_Interessen_03 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Moodboards_Interessen_03_confirmed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Moodboards_Interessen_04 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Moodboards_Interessen_04_confirmed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int moodboards_Standards_01 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int moodboards_Standards_01_confirmed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Moodboards_Standards_02 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Moodboards_Standards_02_confirmed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Moodboards_Standards_03 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Moodboards_Standards_03_confirmed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Moodboards_Standards_04 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Moodboards_Standards_04_confirmed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int nationalparkthy = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int naturgewaltensylt = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int personFour = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int personOne = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int personOneConfirmed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int personThree = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int personTwo = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int piocountryclub = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int PreviewLnR = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int PreviewLtoRTemplate = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int PreviewRnL = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int PreviewRtoLTemplate = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int romo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int roundedbutton = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int schlosskronborg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int schlossrosenborg = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int skagensmuseum = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int skagenstrand = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int sneglehuset = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ufomonument = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Viech_GOwl_alleine_mini = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int wikingermuseum = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int BackgroundExistingJourney = 2131165184;
			
			// aapt resource value: 0x7f07003b
			public const int CalendarLayoutEnd = 2131165243;
			
			// aapt resource value: 0x7f070033
			public const int CalendarLayoutStart = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int CalendarSubLayout = 2131165237;
			
			// aapt resource value: 0x7f07003c
			public const int ChooseEndDateText = 2131165244;
			
			// aapt resource value: 0x7f070034
			public const int ChooseStartDateText = 2131165236;
			
			// aapt resource value: 0x7f070055
			public const int ConnectionLineOne = 2131165269;
			
			// aapt resource value: 0x7f070051
			public const int ConnectionLineTwo = 2131165265;
			
			// aapt resource value: 0x7f07003d
			public const int DatePickerEnd = 2131165245;
			
			// aapt resource value: 0x7f070036
			public const int DatePickerStart = 2131165238;
			
			// aapt resource value: 0x7f07000f
			public const int EndDate = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int ExistingNewJourney = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int ExistingNewJourneyYes = 2131165193;
			
			// aapt resource value: 0x7f070050
			public const int ImageButtonPreviewLtoR = 2131165264;
			
			// aapt resource value: 0x7f070053
			public const int ImageButtonPreviewRtoL = 2131165267;
			
			// aapt resource value: 0x7f07001c
			public const int ImageChoosingExplanation = 2131165212;
			
			// aapt resource value: 0x7f07004f
			public const int JourneyPartLtoR = 2131165263;
			
			// aapt resource value: 0x7f070052
			public const int JourneyPartRtoL = 2131165266;
			
			// aapt resource value: 0x7f070037
			public const int LayoutCalendarNextBack = 2131165239;
			
			// aapt resource value: 0x7f070018
			public const int LayoutNextBackButton = 2131165208;
			
			// aapt resource value: 0x7f07000b
			public const int LinearLayoutPreviewMain = 2131165195;
			
			// aapt resource value: 0x7f070021
			public const int MainPreferences = 2131165217;
			
			// aapt resource value: 0x7f07000a
			public const int NewExistingJourneyBack = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int NewJourneyButton = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int NewMainPreferences = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int NewSearchButton = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int ResetExplanation = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int ScrollViewMain = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int StartingDate = 2131165198;
			
			// aapt resource value: 0x7f07004b
			public const int UnfoldDescription = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int UnfoldDuration = 2131165262;
			
			// aapt resource value: 0x7f07004a
			public const int UnfoldImage = 2131165258;
			
			// aapt resource value: 0x7f070049
			public const int UnfoldPreviewTemplate = 2131165257;
			
			// aapt resource value: 0x7f07004c
			public const int UnfoldSeeker = 2131165260;
			
			// aapt resource value: 0x7f070012
			public const int UserDataButton = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int VoiceResultText = 2131165188;
			
			// aapt resource value: 0x7f070017
			public const int autoCompleteTextView1 = 2131165207;
			
			// aapt resource value: 0x7f070032
			public const int backButton = 2131165234;
			
			// aapt resource value: 0x7f070020
			public const int backButtonChoosing = 2131165216;
			
			// aapt resource value: 0x7f07003f
			public const int backButtonDateEnd = 2131165247;
			
			// aapt resource value: 0x7f07003a
			public const int backButtonDateStart = 2131165242;
			
			// aapt resource value: 0x7f07001b
			public const int backButtonName = 2131165211;
			
			// aapt resource value: 0x7f070045
			public const int backButtonPersonCount = 2131165253;
			
			// aapt resource value: 0x7f070016
			public const int backButtonUserData = 2131165206;
			
			// aapt resource value: 0x7f070054
			public const int date = 2131165268;
			
			// aapt resource value: 0x7f070022
			public const int fullScreenLayout = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int gowlExplanation = 2131165213;
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f07002b
			public const int imageView2 = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int imageView3 = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int imageView4 = 2131165232;
			
			// aapt resource value: 0x7f070040
			public const int imageView5 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int imageView6 = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int imageView7 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int imageView8 = 2131165251;
			
			// aapt resource value: 0x7f070029
			public const int layoutFirstImage = 2131165225;
			
			// aapt resource value: 0x7f07002f
			public const int layoutFourthImage = 2131165231;
			
			// aapt resource value: 0x7f07002c
			public const int layoutLowerImageLine = 2131165228;
			
			// aapt resource value: 0x7f07002a
			public const int layoutSecondImage = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int layoutThirdImage = 2131165229;
			
			// aapt resource value: 0x7f070028
			public const int layoutUpperImageLine = 2131165224;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout2 = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout3 = 2131165205;
			
			// aapt resource value: 0x7f07004d
			public const int linearLayout4 = 2131165261;
			
			// aapt resource value: 0x7f070047
			public const int logo = 2131165255;
			
			// aapt resource value: 0x7f070031
			public const int nextButton = 2131165233;
			
			// aapt resource value: 0x7f07001e
			public const int nextButtonChoosing = 2131165214;
			
			// aapt resource value: 0x7f07003e
			public const int nextButtonDateEnd = 2131165246;
			
			// aapt resource value: 0x7f070038
			public const int nextButtonDateStart = 2131165240;
			
			// aapt resource value: 0x7f070019
			public const int nextButtonName = 2131165209;
			
			// aapt resource value: 0x7f070044
			public const int nextButtonPersonCount = 2131165252;
			
			// aapt resource value: 0x7f07000c
			public const int scrollView1 = 2131165196;
			
			// aapt resource value: 0x7f07001a
			public const int space2 = 2131165210;
			
			// aapt resource value: 0x7f070039
			public const int spaceCalendar = 2131165241;
			
			// aapt resource value: 0x7f07001f
			public const int spaceChoosing = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int spaceUp = 2131165219;
			
			// aapt resource value: 0x7f070048
			public const int startButton = 2131165256;
			
			// aapt resource value: 0x7f070024
			public const int takeItFirst = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int takeItFourth = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int takeItSecond = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int takeItThird = 2131165222;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			// aapt resource value: 0x7f070046
			public const int textView2 = 2131165254;
			
			// aapt resource value: 0x7f070001
			public const int viewFlipper1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int voiceButton = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ExistingJourney = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int JourneyPreview = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainPreferencesName = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MainPreferencesPhaseOne = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int MainPreferencesPhaseThree = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int MainPreferencesPhaseTwo = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int NewJourneyCalendar = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int NewJourneyPersonCount = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int NewJourneySpecificPreferences = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int WelcomeScreen = 2130968586;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int GOwl_Logo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int AkkuAufladen2 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int BisBald = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Fiskrestaurant = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int HeyWasGibts = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int HierSindWir = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int IchBinGowl = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int InformationNationalparkTys = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int KommtMit = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int MuseumSkagen = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int NationalparkUndSneglehuset = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int RecherchierenRestaurant = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int RichtigVerstanden = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int SehrGerne = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int StrandVonSkagen = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int VogelArtenOrt = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Warten = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int WirSehenUns = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int WirSindDa = 2131034129;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
