#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GOWL.Resource", IsApplication=true)]

namespace GOWL
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Logo_komplett_Final_mini = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int test = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int test_test = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Viech_GOwl_alleine_mini = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int worldclear = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int BackgroundExistingJourney = 2131165184;
			
			// aapt resource value: 0x7f070037
			public const int CalendarLayoutEnd = 2131165239;
			
			// aapt resource value: 0x7f07002f
			public const int CalendarLayoutStart = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int CalendarSubLayout = 2131165233;
			
			// aapt resource value: 0x7f070038
			public const int ChooseEndDateText = 2131165240;
			
			// aapt resource value: 0x7f070030
			public const int ChooseStartDateText = 2131165232;
			
			// aapt resource value: 0x7f070039
			public const int DatePickerEnd = 2131165241;
			
			// aapt resource value: 0x7f070032
			public const int DatePickerStart = 2131165234;
			
			// aapt resource value: 0x7f070022
			public const int ImageChoosingExplanation = 2131165218;
			
			// aapt resource value: 0x7f070007
			public const int ImagePart1 = 2131165191;
			
			// aapt resource value: 0x7f070033
			public const int LayoutCalendarNextBack = 2131165235;
			
			// aapt resource value: 0x7f07001e
			public const int LayoutNextBackButton = 2131165214;
			
			// aapt resource value: 0x7f070005
			public const int LinearLayoutPreviewMain = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int MainPreferences = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int NewJourneyButton = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int NewMainPreferences = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int ResetExplanation = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int UserDataButton = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int VoiceResultText = 2131165188;
			
			// aapt resource value: 0x7f070028
			public const int autoCompleteTextView1 = 2131165224;
			
			// aapt resource value: 0x7f070021
			public const int backButton = 2131165217;
			
			// aapt resource value: 0x7f070036
			public const int backButtonCalendar = 2131165238;
			
			// aapt resource value: 0x7f070027
			public const int backButtonChoosing = 2131165223;
			
			// aapt resource value: 0x7f07002a
			public const int backButtonName = 2131165226;
			
			// aapt resource value: 0x7f070010
			public const int backButtonUserData = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int fullScreenLayout = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int gowlExplanation = 2131165220;
			
			// aapt resource value: 0x7f07000b
			public const int imageView1 = 2131165195;
			
			// aapt resource value: 0x7f070018
			public const int imageView2 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int imageView3 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int imageView4 = 2131165213;
			
			// aapt resource value: 0x7f070016
			public const int layoutFirstImage = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int layoutFourthImage = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int layoutLowerImageLine = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int layoutSecondImage = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int layoutThirdImage = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int layoutUpperImageLine = 2131165205;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout2 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout3 = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int listView1 = 2131165192;
			
			// aapt resource value: 0x7f07003c
			public const int logo = 2131165244;
			
			// aapt resource value: 0x7f07001f
			public const int nextButton = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int nextButtonChoosing = 2131165221;
			
			// aapt resource value: 0x7f07003a
			public const int nextButtonDateEnd = 2131165242;
			
			// aapt resource value: 0x7f070034
			public const int nextButtonDateStart = 2131165236;
			
			// aapt resource value: 0x7f070029
			public const int nextButtonName = 2131165225;
			
			// aapt resource value: 0x7f070006
			public const int scrollView1 = 2131165190;
			
			// aapt resource value: 0x7f070020
			public const int space2 = 2131165216;
			
			// aapt resource value: 0x7f070035
			public const int spaceCalendar = 2131165237;
			
			// aapt resource value: 0x7f070026
			public const int spaceChoosing = 2131165222;
			
			// aapt resource value: 0x7f070013
			public const int spaceUp = 2131165203;
			
			// aapt resource value: 0x7f07003d
			public const int startButton = 2131165245;
			
			// aapt resource value: 0x7f070014
			public const int takeIt = 2131165204;
			
			// aapt resource value: 0x7f07002b
			public const int takeItFirst = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int takeItFourth = 2131165230;
			
			// aapt resource value: 0x7f07002c
			public const int takeItSecond = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int takeItThird = 2131165229;
			
			// aapt resource value: 0x7f070023
			public const int textView1 = 2131165219;
			
			// aapt resource value: 0x7f07003b
			public const int textView2 = 2131165243;
			
			// aapt resource value: 0x7f070001
			public const int viewFlipper1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int voiceButton = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ExistingJourney = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int JourneyPreview = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainPreferences = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MainPreferencesName = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int NewJourney = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int WelcomeScreen = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int GOwl_Logo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int AkkuAufladen2 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int BisBald = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Fiskrestaurant = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int HeyWasGibts = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int HierSindWir = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int IchBinGowl = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int InformationNationalparkTys = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int KommtMit = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int MuseumSkagen = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int NationalparkUndSneglehuset = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int RecherchierenRestaurant = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int RichtigVerstanden = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int StrandVonSkagen = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int VogelArtenOrt = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int Warten = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int WirSehenUns = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int WirSindDa = 2131034128;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
